
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      data-locations:
        classpath*: static/data.sql
      mode: always

  Servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB